arch: "vit_base_patch16_224"

tune_type: 'full'
stage_num: 0
prompt_num: 10
init: "xavier_uniform"

m: 0.99
teacher_temp: 0.07
student_temp: 0.1
out_dim: 65536
nlayer_head: 3

consistency_type: 'cls'
hierarchy: False

src_log_dir: None
post_load: False
